// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDawONFA5JOOG4bxtfznQgBeYzti-OVVKY',
    appId: '1:227265967291:web:4aa5eb2322413436e2a59e',
    messagingSenderId: '227265967291',
    projectId: 'whatsapp-master-891f4',
    authDomain: 'whatsapp-master-891f4.firebaseapp.com',
    databaseURL: 'https://whatsapp-master-891f4-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-master-891f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYc96R-jLFCoTxM9AA2_D5yiRFHHcCSjg',
    appId: '1:227265967291:android:9e4e96d8438f855ae2a59e',
    messagingSenderId: '227265967291',
    projectId: 'whatsapp-master-891f4',
    databaseURL: 'https://whatsapp-master-891f4-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-master-891f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe_0VTNl4lHPG9uIwA49eASxNYHX79CmE',
    appId: '1:227265967291:ios:3640f7d7eed5d7c6e2a59e',
    messagingSenderId: '227265967291',
    projectId: 'whatsapp-master-891f4',
    databaseURL: 'https://whatsapp-master-891f4-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-master-891f4.appspot.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
